<?php

namespace AppBundle\Repository;

/**
 * AvisLieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisLieuRepository extends \Doctrine\ORM\EntityRepository
{

//    récupére les avis qui remplisse les paramètre rentrés dans le formulaire de recherche
    public function getMarkersSelonRecherche($note = 0 ,
                                             $supermarche = "supermarche",
                                             $epicerie = "epicerie",
                                             $boulangerie = "boulangerie",
                                             $marche = "marche",
                                             $autre = "autre",
                                             $facile = "facile",
                                             $difficile = "difficile",
                                             $jour = ""){


        if ($jour !== "") {
            return $this->createQueryBuilder('a')
                ->andWhere("a.jourSemaine IN ('$jour')")
                ->leftJoin('a.lieu', 'l')
                ->addSelect('l')
                ->andWhere('l.type IN (:supermarche, :epicerie, :boulangerie, :marche, :autre) AND l.acces IN (:facile, :difficile)')
                ->setParameters(array(
                    'supermarche' => $supermarche,
                    'epicerie' => $epicerie,
                    'boulangerie' => $boulangerie,
                    'marche' => $marche,
                    'autre' => $autre,
                    'facile' => $facile,
                    'difficile' => $difficile,
                ))
                ->getQuery()
                ->getResult();
        }

        else {
            return $this->createQueryBuilder('a')
                ->leftJoin('a.lieu', 'l')
                ->addSelect('l')
                ->andWhere('l.type IN (:supermarche, :epicerie, :boulangerie, :marche, :autre) AND l.acces IN (:facile, :difficile)')
                ->setParameters(array(
                    'supermarche' => $supermarche,
                    'epicerie' => $epicerie,
                    'boulangerie' => $boulangerie,
                    'marche' => $marche,
                    'autre' => $autre,
                    'facile' => $facile,
                    'difficile' => $difficile,
                ))
                ->getQuery()
                ->getResult();
        }
    }

}
