<?php

namespace AppBundle\Repository;

/**
 * DescriptionLieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptionLieuRepository extends \Doctrine\ORM\EntityRepository
{


}
