<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{

	public function getAllEvents(){
		return $this->getEntityManager()
					->createQuery('
						SELECT e FROM AppBundle:Evenement e ORDER BY e.day DESC')
					->getResult();
	}
	public function getSeveralEventsByCreated($firstResult = 0){


		return $this->getEntityManager()
					->createQuery('
						SELECT e FROM AppBundle:Evenement e ORDER BY e.created DESC ')
					->setFirstResult($firstResult)
					->setMaxResults(6)
					->getResult();
	}

	/**
	 * @return mixed
	 * @throws \Doctrine\ORM\NonUniqueResultException
	 * recupère le nombre d'événements total présent dans la base de donnée
	 */
	public function getNumberEvents()
	{
		return $this->getEntityManager()
			->createQuery('
						SELECT COUNT(e.id) FROM AppBundle:Evenement e')
			->getOneOrNullResult();
	}


}
