services:
    app_bundle.app.gestion_formulaire:
        class:  AppBundle\Services\GestionFormulaire
        arguments: [ "@doctrine.orm.entity_manager", "@form.factory", "@security.authentication_utils", "@mailer", "@session"]

    app_bundle.app.gestion_formulaire_carte:
        class:  AppBundle\Services\GestionFormulaireCarte
        arguments: [ "@doctrine.orm.entity_manager", "@form.factory" ]

    app_bundle.app.gestion_affichage_carte:
        class:  AppBundle\Services\GestionAffichageCarte
        arguments: [ "@doctrine.orm.entity_manager" ]
