services:
    app_bundle.app.gestion_formulaire:
        class:  AppBundle\Services\GestionFormulaire
        arguments: [ "@doctrine.orm.entity_manager", "@form.factory", "@security.authentication_utils", "@mailer", "@session"]
