parameters:
  app_max_tab:
    - 1
    - 2 
    - 3

services:
  app_lorem:
    class: AppBundle\Twig\LoremTwig
    tags:
        - name: twig.extension
  app_random:
    class: AppBundle\Services\Random
    arguments:
      - 1
      - 100
  app_max:
    class: AppBundle\Services\Max
    arguments: [ "@=container.hasParameter('app_max_tab') ? parameter('app_max_tab') : service('app_random').generateRandomNumbers()", "@request_stack" ]
    calls:
      - [ changeRandoms, ['@app_max'] ]
  app_date:
    class: AppBundle\Listener\AddDate
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: putDate }
